<?php
/**
 * AnalyticsFilterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yext\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yext API
 *
 * 
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yext\Client;

/**
 * AnalyticsFilterTest Class Doc Comment
 *
 * @category    Class */
// * @description AnalyticsFilter
/**
 * @package     Yext\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AnalyticsFilterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AnalyticsFilter"
     */
    public function testAnalyticsFilter()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "location_labels"
     */
    public function testPropertyLocationLabels()
    {

    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {

    }

    /**
     * Test attribute "instagram_content_type"
     */
    public function testPropertyInstagramContentType()
    {

    }

    /**
     * Test attribute "google_action_type"
     */
    public function testPropertyGoogleActionType()
    {

    }

    /**
     * Test attribute "google_query_type"
     */
    public function testPropertyGoogleQueryType()
    {

    }

    /**
     * Test attribute "platforms"
     */
    public function testPropertyPlatforms()
    {

    }

    /**
     * Test attribute "search_term"
     */
    public function testPropertySearchTerm()
    {

    }

    /**
     * Test attribute "partners"
     */
    public function testPropertyPartners()
    {

    }

    /**
     * Test attribute "search_type"
     */
    public function testPropertySearchType()
    {

    }

    /**
     * Test attribute "foursquare_checkin_age"
     */
    public function testPropertyFoursquareCheckinAge()
    {

    }

    /**
     * Test attribute "frequent_words"
     */
    public function testPropertyFrequentWords()
    {

    }

    /**
     * Test attribute "foursquare_checkin_time_of_day"
     */
    public function testPropertyFoursquareCheckinTimeOfDay()
    {

    }

    /**
     * Test attribute "ratings"
     */
    public function testPropertyRatings()
    {

    }

    /**
     * Test attribute "foursquare_checkin_gender"
     */
    public function testPropertyFoursquareCheckinGender()
    {

    }

    /**
     * Test attribute "foursquare_checkin_type"
     */
    public function testPropertyFoursquareCheckinType()
    {

    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {

    }

    /**
     * Test attribute "max_search_frequency"
     */
    public function testPropertyMaxSearchFrequency()
    {

    }

    /**
     * Test attribute "folder_id"
     */
    public function testPropertyFolderId()
    {

    }

    /**
     * Test attribute "location_ids"
     */
    public function testPropertyLocationIds()
    {

    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {

    }

    /**
     * Test attribute "min_search_frequency"
     */
    public function testPropertyMinSearchFrequency()
    {

    }

}
