<?php
/**
 * PostEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yext\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yext API
 *
 * 
 *
 * OpenAPI spec version: 0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yext\Client;

/**
 * PostEntryTest Class Doc Comment
 *
 * @category    Class */
// * @description PostEntry
/**
 * @package     Yext\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PostEntry"
     */
    public function testPostEntry()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "liked"
     */
    public function testPropertyLiked()
    {

    }

    /**
     * Test attribute "author"
     */
    public function testPropertyAuthor()
    {

    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {

    }

    /**
     * Test attribute "photo_url"
     */
    public function testPropertyPhotoUrl()
    {

    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "likes"
     */
    public function testPropertyLikes()
    {

    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {

    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {

    }

    /**
     * Test attribute "publisher_id"
     */
    public function testPropertyPublisherId()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "link_url"
     */
    public function testPropertyLinkUrl()
    {

    }

}
