<?php
/**
 * LocationManagerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yext\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yext API
 *
 * 
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yext\Client;

use \Yext\Client\Configuration;
use \Yext\Client\ApiClient;
use \Yext\Client\ApiException;
use \Yext\Client\ObjectSerializer;

/**
 * LocationManagerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yext\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LocationManagerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createBio
     *
     * Bios: Create.
     *
     */
    public function testCreateBio()
    {

    }

    /**
     * Test case for createEvent
     *
     * Events: Create.
     *
     */
    public function testCreateEvent()
    {

    }

    /**
     * Test case for createLocation
     *
     * Locations: Create.
     *
     */
    public function testCreateLocation()
    {

    }

    /**
     * Test case for createMenu
     *
     * Menus: Create.
     *
     */
    public function testCreateMenu()
    {

    }

    /**
     * Test case for createProduct
     *
     * Products: Create.
     *
     */
    public function testCreateProduct()
    {

    }

    /**
     * Test case for deleteBioList
     *
     * Bios: Delete.
     *
     */
    public function testDeleteBioList()
    {

    }

    /**
     * Test case for deleteEventList
     *
     * Events: Delete.
     *
     */
    public function testDeleteEventList()
    {

    }

    /**
     * Test case for deleteLanguageProfile
     *
     * Language Profiles: Delete.
     *
     */
    public function testDeleteLanguageProfile()
    {

    }

    /**
     * Test case for deleteMenuList
     *
     * Menus: Delete.
     *
     */
    public function testDeleteMenuList()
    {

    }

    /**
     * Test case for deleteProductList
     *
     * Products: Delete.
     *
     */
    public function testDeleteProductList()
    {

    }

    /**
     * Test case for getBio
     *
     * Bios: Get.
     *
     */
    public function testGetBio()
    {

    }

    /**
     * Test case for getBios
     *
     * Bios: List.
     *
     */
    public function testGetBios()
    {

    }

    /**
     * Test case for getBusinessCategories
     *
     * Categories: List.
     *
     */
    public function testGetBusinessCategories()
    {

    }

    /**
     * Test case for getCustomFields
     *
     * Custom Fields: List.
     *
     */
    public function testGetCustomFields()
    {

    }

    /**
     * Test case for getEvent
     *
     * Events: Get.
     *
     */
    public function testGetEvent()
    {

    }

    /**
     * Test case for getEvents
     *
     * Events: List.
     *
     */
    public function testGetEvents()
    {

    }

    /**
     * Test case for getGoogleKeywords
     *
     * Google Fields: List.
     *
     */
    public function testGetGoogleKeywords()
    {

    }

    /**
     * Test case for getLanguageProfile
     *
     * Language Profiles: Get.
     *
     */
    public function testGetLanguageProfile()
    {

    }

    /**
     * Test case for getLanguageProfiles
     *
     * Language Profiles: List.
     *
     */
    public function testGetLanguageProfiles()
    {

    }

    /**
     * Test case for getLocation
     *
     * Locations: Get.
     *
     */
    public function testGetLocation()
    {

    }

    /**
     * Test case for getLocationFolders
     *
     * Folders: List.
     *
     */
    public function testGetLocationFolders()
    {

    }

    /**
     * Test case for getLocations
     *
     * Locations: List.
     *
     */
    public function testGetLocations()
    {

    }

    /**
     * Test case for getMenu
     *
     * Menus: Get.
     *
     */
    public function testGetMenu()
    {

    }

    /**
     * Test case for getMenus
     *
     * Menus: List.
     *
     */
    public function testGetMenus()
    {

    }

    /**
     * Test case for getProduct
     *
     * Products: Get.
     *
     */
    public function testGetProduct()
    {

    }

    /**
     * Test case for getProducts
     *
     * Products: List.
     *
     */
    public function testGetProducts()
    {

    }

    /**
     * Test case for updateBio
     *
     * Bios: Update.
     *
     */
    public function testUpdateBio()
    {

    }

    /**
     * Test case for updateEvent
     *
     * Events: Update.
     *
     */
    public function testUpdateEvent()
    {

    }

    /**
     * Test case for updateLocation
     *
     * Locations: Update.
     *
     */
    public function testUpdateLocation()
    {

    }

    /**
     * Test case for updateMenu
     *
     * Menus: Update.
     *
     */
    public function testUpdateMenu()
    {

    }

    /**
     * Test case for updateProduct
     *
     * Products: Update.
     *
     */
    public function testUpdateProduct()
    {

    }

    /**
     * Test case for upsertLanguageProfile
     *
     * Language Profiles: Upsert.
     *
     */
    public function testUpsertLanguageProfile()
    {

    }

}
